[project]
name = "studymateai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bhoomikaaa20", email = "bhoomikasomavarapu15@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.5",
    "langchain-huggingface>=1.2.2",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
studymateai = "studymateai:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
